export const conflicts = [
  {
    name: "Russia-Ukraine War",
    country_team1: ["Russia"],
    country_team2: ["Ukraine"],
    type: "War",
    status: "Ongoing",
    flags: ["url_to_country_x_flag", "url_to_country_y_flag"],
    position: [48.379433, 31.165579],
    description: "The official war in Ukraine started in 2022, but the conflict began in 2014. The war is still ongoing. Russia has annexed Crimea and supports separatists in Eastern Ukraine and trying to take over the whole country.",
    date: "2022 - Present",
    deaths: 14000,
  },
  {
    name: "Israel-Palestine War",
    country_team1: ["Israel"],
    country_team2: ["Palestine", "Hamas", "Hezbollah", "Islamic Jihad"],
    type: "War",
    status: "Ongoing",
    flags: ["url_to_country_x_flag", "url_to_country_y_flag"],
    position: [31.046051, 34.851612],
    description: "The conflict started in 2023 and is still ongoing",
    date: "2023 - Present",
  },
  {
    name: "China-India Border Conflict",
    country_team1: ["China"],
    country_team2: ["India"],
    type: "Tension",
    status: "Ongoing",
    flags: ["url_to_country_x_flag", "url_to_country_y_flag"],
    position: [34.047863, 78.429756],
    description: "The conflict started in 2020 and is still ongoing",
    date: "2020 - Present",
  },
  {
    name: "China-Taiwan Conflict",
    country_team1: ["China"],
    country_team2: ["Taiwan"],
    type: "Tension",
    status: "Ongoing",
    flags: ["url_to_country_x_flag", "url_to_country_y_flag"],
    position: [23.69781, 120.960515],
    description: "The conflict started in 1949 and is still ongoing",
    date: "1949 - Present",
  },
  {
    name: "Russia-Georgia War",
    country_team1: ["Russia"],
    country_team2: ["Georgia"],
    type: "War",
    status: "Ongoing",
    flags: ["url_to_country_x_flag", "url_to_country_y_flag"],
    position: [42.315407, 43.356892],
    description: "The conflict started in 2008 and is still ongoing",
    date: "2008 - Present",
  },
  {
    name: "Saudi Arabia-Yemen War",
    country_team1: ["Saudi Arabia"],
    country_team2: ["Yemen", "Houthis"],
    type: "War",
    status: "Ongoing",
    flags: ["url_to_country_x_flag", "url_to_country_y_flag"],
    position: [15.552727, 48.516388],
    description: "The conflict started in 2015 and is still ongoing",
    date: "2015 - Present",
  },
  {
    name: "Turkey-Syria War",
    country_team1: ["Turkey"],
    country_team2: ["Syria", "Kurds"],
    type: "War",
    status: "Ongoing",
    flags: ["url_to_country_x_flag", "url_to_country_y_flag"],
    position: [35.86166, 38.281635],
    description: "The conflict started in 2011 and is still ongoing",
    date: "2011 - Present",
  },
  {
    name: "Venezuela Guiana Esequiba Conflict",
    country_team1: ["Venezuela"],
    country_team2: ["Guyana"],
    type: "Tension",
    status: "Ongoing",
    flags: ["url_to_country_x_flag", "url_to_country_y_flag"],
    position: [6.806071, -58.154968],
    description: "The conflict started in 1966 and is still ongoing",
    date: "1966 - Present",
  },
  {
    name: "United States-Iran Conflict",
    country_team1: ["United States"],
    country_team2: ["Iran"],
    type: "Tension",
    status: "Ongoing",
    flags: ["url_to_country_x_flag", "url_to_country_y_flag"],
    position: [32.427908, 53.688046],
    description: "The conflict started in 1979 and is still ongoing",
    date: "1979 - Present",
  },
  {
    name: "United States-North Korea Conflict",
    country_team1: ["United States"],
    country_team2: ["North Korea"],
    type: "Tension",
    status: "Ongoing",
    flags: ["url_to_country_x_flag", "url_to_country_y_flag"],
    position: [40.339852, 127.510093],
    description: "The conflict started in 1950 and is still ongoing",
    date: "1950 - Present",
  },
  {
    name: "United States-Russia Conflict",
    country_team1: ["United States"],
    country_team2: ["Russia"],
    type: "Tension",
    status: "Ongoing",
    flags: ["url_to_country_x_flag", "url_to_country_y_flag"],
    position: [61.52401, -105.318756],
    description: "The conflict started in 2014 and is still ongoing",
    date: "2014 - Present",
  },
  {
    name: "United States-China Conflict",
    country_team1: ["United States"],
    country_team2: ["China"],
    type: "Tension",
    status: "Ongoing",
    flags: ["url_to_country_x_flag", "url_to_country_y_flag"],
    position: [35.86166, 104.195397],
    description: "The conflict started in 2018 and is still ongoing",
    date: "2018 - Present",
  },
  {
    name: "United States-Venezuela Conflict",
    country_team1: ["United States"],
    country_team2: ["Venezuela"],
    type: "Tension",
    status: "Ongoing",
    flags: ["url_to_country_x_flag", "url_to_country_y_flag"],
    position: [6.42375, -66.58973],
    description: "The conflict started in 2019 and is still ongoing",
    date: "2019 - Present",
  },
];